In [ ]:
import pandas as pd

event = pd.read_csv('output_anomalies/RF_run_with_lagged_et01_event.csv')


poor_sites = pd.read_csv(
    "poor_performance_sites.csv"
)

event_filtered = event[~event["SITE_ID"].isin(poor_sites["SITE_ID"])]

anomalies_per_site = (
    event_filtered
    .groupby("SITE_ID")
    .size()
    .reset_index(name="num_anomalies")
)

(anomalies_per_site)

   SITE_ID  num_anomalies
0   AU-ASM             28
1   AU-Cpr             43
2   AU-Dry             30
3   AU-Gin             31
4   AU-How             13
5   AU-RDF             23
6   AU-Rig             41
7   AU-Stp             47
8   AU-TTE             30
9   AU-Wom             12
10  BE-Vie              5
11  CA-NS4             14
12  CA-Oas             22
13  CA-SF1             40
14  CA-SF2             38
15  CA-TPD              6
16  CH-Cha             19
17  CH-Oe1             12
18  CN-Cha             31
19  CN-Dan             15
20  CN-Din              7
21  CN-Qia             16
22  DE-Gri              3
23  DE-Hai             36
24  DE-Obe              4
25  DE-Tha             16
26  DK-Sor             14
27  ES-LJu              4
28  IT-CA1             11
29  IT-CA3              3
30  IT-Cpz             63
31  IT-Isp             15
32  IT-Noe             34
33  IT-Ro1             53
34  IT-SRo             77
35  JP-SMF             50
36  NL-Loo             44
37  PA-SPn              3
38  PA-SPs             13
39  RU-Ha1             22
40  SD-Dem             36
41  US-AR1             24
42  US-ARb             12
43  US-ARc             16
44  US-Blo              4
45  US-Goo             35
46  US-IB2              6
47  US-KS1             11
48  US-KS2             27
49  US-LWW             13
50  US-Oho              6
51  US-SRC             18
52  US-SRG              6
53  US-SRM             75
54  US-Syv             17
55  US-Ton            104
56  US-Var            141
57  US-WCr             39
58  US-Whs             53
59  US-Wkg            120

In [ ]:
import pandas as pd
import numpy as np

uncertainty = pd.read_csv('output_anomalies/RF_run_with_lagged_et01_testuncertainty.csv')

event_filtered = event_filtered.merge(
    uncertainty[["SITE_ID", "p25", "p75"]],
    on="SITE_ID",
    how="left"
)

event_filtered["outside_IQR"] = (
    (event_filtered["actual - predicted"] < event_filtered["p25"]) |
    (event_filtered["actual - predicted"] > event_filtered["p75"])
)
outside_range = (
    event_filtered
    .groupby("SITE_ID")["outside_IQR"]
    .sum()
    .reset_index(name="num_anomalies_outside_IQR")
)

outside_range

   SITE_ID  num_anomalies_outside_IQR
0   AU-ASM                         28
1   AU-Cpr                         28
2   AU-Dry                         23
3   AU-Gin                         21
4   AU-How                         11
5   AU-RDF                         22
6   AU-Rig                         20
7   AU-Stp                         45
8   AU-TTE                         29
9   AU-Wom                          5
10  BE-Vie                          4
11  CA-NS4                         10
12  CA-Oas                          5
13  CA-SF1                         17
14  CA-SF2                         19
15  CA-TPD                          3
16  CH-Cha                          9
17  CH-Oe1                          7
18  CN-Cha                         16
19  CN-Dan                         12
20  CN-Din                          4
21  CN-Qia                         12
22  DE-Gri                          2
23  DE-Hai                         16
24  DE-Obe                          3
25  DE-Tha                          8
26  DK-Sor                         13
27  ES-LJu                          2
28  IT-CA1                          6
29  IT-CA3                          1
30  IT-Cpz                         29
31  IT-Isp                          2
32  IT-Noe                         17
33  IT-Ro1                         31
34  IT-SRo                         66
35  JP-SMF                         35
36  NL-Loo                         28
37  PA-SPn                          1
38  PA-SPs                          8
39  RU-Ha1                         19
40  SD-Dem                         34
41  US-AR1                         21
42  US-ARb                          7
43  US-ARc                         11
44  US-Blo                          4
45  US-Goo                         17
46  US-IB2                          5
47  US-KS1                          3
48  US-KS2                         17
49  US-LWW                         10
50  US-Oho                          3
51  US-SRC                         18
52  US-SRG                          6
53  US-SRM                         66
54  US-Syv                         10
55  US-Ton                         78
56  US-Var                        104
57  US-WCr                         28
58  US-Whs                         53
59  US-Wkg                        111

In [37]:
outside_range.shape[0]

60

In [45]:
outside_range[outside_range["num_anomalies_outside_IQR"] > 4].shape[0]

48

In [54]:
comparison = anomalies_per_site.merge(
    outside_range,
    on="SITE_ID",
    how="left"
)

comparison["num_anomalies_outside_IQR"] = comparison["num_anomalies_outside_IQR"]
comparison["% of anomalies outside range"] = round(comparison["num_anomalies_outside_IQR"] / comparison["num_anomalies"] * 100, 2)

comparison

,SITE_ID,num_anomalies,num_anomalies_outside_IQR,% of anomalies outside range
0,AU-ASM,28,28,100.00
1,AU-Cpr,43,28,65.12
2,AU-Dry,30,23,76.67
3,AU-Gin,31,21,67.74
4,AU-How,13,11,84.62
5,AU-RDF,23,22,95.65
6,AU-Rig,41,20,48.78
7,AU-Stp,47,45,95.74
8,AU-TTE,30,29,96.67
9,AU-Wom,12,5,41.67
10,BE-Vie,5,4,80.00
11,CA-NS4,14,10,71.43
12,CA-Oas,22,5,22.73
13,CA-SF1,40,17,42.50
14,CA-SF2,38,19,50.00
15,CA-TPD,6,3,50.00
16,CH-Cha,19,9,47.37
17,CH-Oe1,12,7,58.33
18,CN-Cha,31,16,51.61
19,CN-Dan,15,12,80.00
20,CN-Din,7,4,57.14
21,CN-Qia,16,12,75.00
22,DE-Gri,3,2,66.67
23,DE-Hai,36,16,44.44
24,DE-Obe,4,3,75.00
25,DE-Tha,16,8,50.00
26,DK-Sor,14,13,92.86
27,ES-LJu,4,2,50.00
28,IT-CA1,11,6,54.55
29,IT-CA3,3,1,33.33
30,IT-Cpz,63,29,46.03
31,IT-Isp,15,2,13.33
32,IT-Noe,34,17,50.00
33,IT-Ro1,53,31,58.49
34,IT-SRo,77,66,85.71
35,JP-SMF,50,35,70.00
36,NL-Loo,44,28,63.64
37,PA-SPn,3,1,33.33
38,PA-SPs,13,8,61.54
39,RU-Ha1,22,19,86.36
40,SD-Dem,36,34,94.44
41,US-AR1,24,21,87.50
42,US-ARb,12,7,58.33
43,US-ARc,16,11,68.75
44,US-Blo,4,4,100.00
45,US-Goo,35,17,48.57
46,US-IB2,6,5,83.33
47,US-KS1,11,3,27.27
48,US-KS2,27,17,62.96
49,US-LWW,13,10,76.92
50,US-Oho,6,3,50.00
51,US-SRC,18,18,100.00
52,US-SRG,6,6,100.00
53,US-SRM,75,66,88.00
54,US-Syv,17,10,58.82
55,US-Ton,104,78,75.00
56,US-Var,141,104,73.76
57,US-WCr,39,28,71.79
58,US-Whs,53,53,100.00
59,US-Wkg,120,111,92.50